# Generated by Django 3.0.6 on 2020-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_emec', models.IntegerField(max_length=8)),
                ('grau_curso', models.IntegerField(max_length=8)),
                ('data_autorização', models.DateTimeField(null=True)),
                ('data_publicacao', models.DateTimeField(null=True)),
                ('data_renovacao', models.DateTimeField(null=True)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('nome_curso', models.CharField(max_length=50)),
            ],
        ),
    ]
