# Generated by Django 3.0.6 on 2020-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='data_publicacao',
            new_name='data_reconhecimento',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='curso',
            name='grau_curso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
