# Generated by Django 3.0.6 on 2020-12-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20201205_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='data_autorização',
            new_name='data_autorizacao',
        ),
    ]
