# Generated by Django 3.0.6 on 2020-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20201206_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cod_emec',
            field=models.TextField(max_length=50),
        ),
    ]
