# Generated by Django 3.0.6 on 2020-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20201209_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cod_emec',
            field=models.TextField(max_length=10),
        ),
    ]
