# Generated by Django 3.0.6 on 2020-12-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0010_auto_20201211_1117'),
        ('curso', '0005_auto_20201211_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_inst',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Par'),
            preserve_default=False,
        ),
    ]
