# Generated by Django 3.0.6 on 2020-12-05 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201205_1045'),
        ('instituicao', '0002_dirigente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('credenciamento', models.IntegerField()),
                ('mantenedora', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='dirigente',
            name='user',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
        migrations.DeleteModel(
            name='Dirigente',
        ),
    ]
