# Generated by Django 3.0.6 on 2020-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0004_auto_20201209_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inst_Parc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('credenciamento', models.IntegerField()),
                ('mantenedora', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('diretor', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='inst_val',
            name='dirigente',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
