# Generated by Django 3.0.6 on 2020-12-10 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instituicao', '0005_auto_20201209_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst_val',
            name='dirigente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
