# Generated by Django 3.0.6 on 2020-12-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0006_auto_20201210_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inst_Parc',
        ),
    ]
