# Generated by Django 3.0.6 on 2020-12-10 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instituicao', '0007_delete_inst_parc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inst_Val',
            new_name='Inst_Par',
        ),
    ]
