# Generated by Django 3.0.6 on 2020-12-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0009_inst_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inst_val',
            old_name='dirigente',
            new_name='superitende',
        ),
    ]
