# Generated by Django 3.0.6 on 2020-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.CharField(max_length=200)),
                ('prioridade', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
