# Generated by Django 3.0.6 on 2020-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201201_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='cpf',
        ),
        migrations.RemoveField(
            model_name='tipo_usuario',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
