# Generated by Django 3.0.6 on 2020-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201205_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
