# Generated by Django 3.0.6 on 2020-12-10 05:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_superval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperVal',
            new_name='DiretorVal',
        ),
    ]
