# Generated by Django 3.0.6 on 2020-12-10 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0009_dirigenteval_superpar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperPar',
            new_name='SuperVal',
        ),
    ]
