# Generated by Django 3.0.6 on 2020-12-14 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0010_auto_20201211_1117'),
        ('registration', '0010_auto_20201210_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Par'),
            preserve_default=False,
        ),
    ]
