# Generated by Django 3.0.6 on 2020-12-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0010_auto_20201211_1117'),
        ('registration', '0011_usuario_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretorpar',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dirigentepar',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dirigenteval',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Val'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superval',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Inst_Val'),
            preserve_default=False,
        ),
    ]
