# Generated by Django 3.0.6 on 2020-12-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20201214_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criada',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Tipo_Usuario'),
            preserve_default=False,
        ),
    ]
