# Generated by Django 3.0.6 on 2020-12-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20201214_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
