# Generated by Django 3.0.6 on 2020-12-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_remove_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
